### ISSUE TITLE
2D scales

### ISSUE THREAD

**Issue by domoritz** [vega/vega-scale#7]
What would be the simplest way to add a 2D scale that takes two variables as input. I would like to create a scale that takes two values or a composed value as input and returns a color that mixes two colors from the two inputs and two different color scales.

**Comment by jheer** [comment]
Currently this is not supported at the Vega JSON spec level, due to vega-parser. (Specifically, [scale.js#L30](https://github.com/vega/vega-parser/blob/master/src/parsers/scale.js#L30).)

To enable custom scales, a number of modifications are needed:
- Update vega-scale to export an enumerable set of defined scale types.
- Update vega-parser to depend on vega-scale and consult an exported scale type registry.
- (Possibly needed) Further update vega-scale to track scale metadata currently hardwired into the parser (e.g., is a scale an ordinal/band/point or quantile scale).

To add a new scale, the basic recipe would then be:
- Implement the scale however you like in JavaScript code.
- Register the scale with Vega under a specific scale type name using [`vega.scale(type, customScale)`](https://github.com/vega/vega-scale#scale) (possibly with additional metadata for use by the parser).

Depending on your use case, you may then run into issues with how to specify the domain, assuming you want control over both input variable domains... and so on. Even with all the above implemented (phew!), you might still end up fighting with parameterization in Vega because scales are assumed to be 1D -> 1D functions. And good luck if you also wanted to be able to generate a legend for your scale...

Instead, you might consider some other possibilities:
- Is there some feasible transformation of your 2D domain to a 1D domain? You might then use some combination of transformation + 1D scale.
- Can your use case be met with a projection (2D -> 2D function) instead? This might work if the domain extents are known implicitly and do not need to be specified (or, you might "hack" your usage of the allowed projection parameters). Unlike scales, projections are currently extensible and usable within Vega JSON specs via the [`vega.projection(type, projection)`](https://github.com/vega/vega-projection/#projection) method. Your "projection" would be a bit of a hack (it might ignore standard projection parameters like scale, rotation, etc), but could accept 2D input and return "1D" output of the form `[value, null]`.

The short answer is that I do not know of a "clean" way to do this...

**Comment by domoritz** [comment]
> Currently this is not supported at the Vega JSON spec level

Not sure what you mean exactly. I am okay with using the Vega API

> To enable custom scales, a number of modifications are needed

I followed https://vega.github.io/vega/docs/api/extensibility/#scales and was able to override an existing scale with itself (`vega.scale('linear', vega.scale('linear'));`). I noticed that I could not add my own scale name although the documentation says "If the scale argument is provided, it must be a scale constructor function to add to the registry under the given type name." To me, this sounds like I would be able to add a new scale. I think the wording could be tweaked to make this clearer. 

> Is there some feasible transformation of your 2D domain to a 1D domain? You might then use some combination of transformation + 1D scale.

I have to think more about this. My initial plan was a custom 1D -> 1D scale where the input has to be a nested object but it sounds like I can't add my own scale/override an existing scale. 

> Can your use case be met with a projection (2D -> 2D function) instead? 

I hadn't thought of that but I don't think I know the domain and range outside of Vega. What I want is a heatmap where I show two measures at once. I think I will have to compute the binning, aggregation, and the define the color scale outside of Vega and use Vega only for rendering. Or I just use size + color or opacity + color.
